---
- name: Create Deluge structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
    owner: MediaServices
    group: MediaServices
    recurse: False
  with_items:
    - path: "/data/DockerMounts/Deluge"
    - path: "/data/DockerMounts/Deluge/Config"

- name: Create and start container
  community.docker.docker_container:
    name: deluge
    image: "linuxserver/deluge"
    published_ports:
      - "58000:58000"
      - "58000:58000/udp"
      - "58001:58001"
      - "58001:58001/udp"
      - "58002:58002"
      - "58002:58002/udp"
      - "127.0.0.1:8112:8112"
    env:
      PUID: "2000"
      PGID: "2000"
      DELUGE_LOGLEVEL: "warning"
    labels:
      traefik.enable: "true"
      traefik.http.routers.deluge.rule: "Host(`deluge.{{domain}}`)"
      traefik.http.routers.deluge.tls.certresolver: "letsencrypt"
      traefik.http.routers.deluge.middlewares: "authelia@docker"
      traefik.http.services.deluge.loadbalancer.server.port: "8112"
    volumes:
      - "/data/DockerMounts/Deluge/Config:/config"
      - "/data/Media/Torrents:/torrents"
      - "/data/Media/Movies:/movies"
      - "/data/Media/:/downloads"
    networks:
      - name: proxy
      - name: plex
