---
- name: Mothership
  hosts: mothership
  vars_files:
    - ["settings.yml", "settings.yml.default"]
  roles:
    - role: system
      tags:
        - base
    - role: common
      tags:
        - base
    - role: docker
      tags:
        - base
    - role: media-server
      tags:
        - base
    - role: nginx-proxy
      tags:
        - proxy
    - role: wordpress
      tags:
        - wordpress
    - role: deluge
      tags:
        - deluge
        - arr
    - role: sonarr
      tags:
        - sonarr
        - arr
    - role: radarr
      tags:
        - radarr
        - arr
    - role: bazarr
      tags:
        - bazarr
        - arr
    - role: plex
      tags:
        - plex
    - role: tautulli
      tags:
        - plex
    - role: wallabag
      tags:
        - wallabag
    - role: unifi
      tags:
        - unifi
    - role: portainer
      tags:
        - docker-tools
    - role: watchtower
      tags:
        - docker-tools
    - role: dolar-ar
      tags:
        - dolar-ar
