---
- name: Mothership
  hosts: mothership
  vars_files:
    - ["settings.yml", "settings.yml.default"]
  module_defaults:
    community.docker.docker_container:
      container_default_behavior: no_defaults
      network_mode: bridge
      purge_networks: yes
      pull: yes
      restart: yes
      restart_policy: unless-stopped
      state: started
  roles:
    - role: system
      tags:
        - base
    - role: common
      tags:
        - base
    - role: docker
      tags:
        - base
    - role: media-server
      tags:
        - base
    - role: netdata
      tags:
        - base
        - netdata
    # - role: nginx-proxy
    #   tags:
    #     - proxy
    - role: traefik
      tags:
        - proxy
    - role: authelia
      tags:
        - auth
    - role: wordpress
      tags:
        - wordpress
    - role: deluge
      tags:
        - deluge
        - arr
    - role: sonarr
      tags:
        - sonarr
        - arr
    - role: radarr
      tags:
        - radarr
        - arr
    - role: bazarr
      tags:
        - bazarr
        - arr
    - role: plex
      tags:
        - plex
    - role: tautulli
      tags:
        - plex
    - role: wallabag
      tags:
        - wallabag
    - role: unifi
      tags:
        - unifi
    - role: portainer
      tags:
        - docker-tools
    - role: watchtower
      tags:
        - docker-tools
    - role: dolar-ar
      tags:
        - dolar-ar
