---
- name: Create and start Watchtower container
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower
    command: --cleanup --interval 15
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
