- name: Create Deluge structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    recurse: "{{ item.recurse }}"
  with_items:
    - path: '/data/DockerMounts/Deluge'
      mode: 770
      owner: Deluge
      group: MediaServices
      recurse: False
    - path: '/data/DockerMounts/Deluge/Config'
      mode: 770
      owner: Deluge
      group: MediaServices
      recurse: True

- name: Create Deluge symlink
  file:
    src: /data/Media
    dest: /data/DockerMounts/Deluge/Media
    state: link
    owner: Deluge
    group: MediaServices

- name: Create Deluge Web TCP IPTable rules
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 8112
    jump: ACCEPT

- name: Create Deluge TCP IPTable rules
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 58000:58030
    jump: ACCEPT

- name: Create Deluge UDP IPTable rules
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: 58000:58030
    jump: ACCEPT
