---
- name: Add Media Server Groups
  tags:
    - users
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  with_items:
    - { name: 'MediaServices', gid: 2004 }
    - { name: 'NGINX', gid: 2005}

- name: Add Media Server Users
  tags:
    - users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    shell: /bin/false
    group: MediaServices
    state: present
  with_items:
    - { name: 'Plex', uid: 2000 }
    - { name: 'Deluge', uid: 2001 }
    - { name: 'Sonarr', uid: 2002 }
    - { name: 'Radarr', uid: 2003 }

- name: Configure Plex
  include: plex.yml
  tags:
    - docker-compose

- name: Configure Sonarr
  include: sonarr.yml
  tags:
    - docker-compose

- name: Configure Radarr
  include: radarr.yml
  tags:
    - docker-compose

- name: Configure Deluge
  include: deluge.yml
  tags:
    - docker-compose

- name: Configure NGINX
  include: nginx.yml
  tags:
    - docker-compose
