- name: Create NGINX structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    recurse: true
  with_items:
    - path: '/data/DockerMounts/NGINX/Config'
      mode: 770
      owner: NGINX
      group: NGINX
    - path: '/data/DockerMounts/NGINX/Config'
      mode: 770
      owner: NGINX
      group: NGINX

- name: Run NGINX docker-compose
  docker_service:
    project_name: nginx
    definition:
      version: '2'
      networks:
        wordpress:
          external:
            name: wordpress_wordpress
        db:
          external:
            name: wordpress_db
        sonarr:
          external:
            name: sonarr_sonarr
        radarr:
          external:
            name: radarr_radarr

      services:
        web:
          image: linuxserver/nginx
          restart: always
          ports:
            - "80:80"
            - "443:443"
          environment:
            - PUID=2006
            - PGID=2005
            - ADVANCED_DISABLEUPDATES=true
          volumes:
            - '/dev/rtc:/dev/rtc:ro'
            - '/etc/localtime:/etc/localtime:ro'
            - '/data/DockerMounts/NGINX/Config:/config'
          networks:
            wordpress:
            db:
            sonarr:
            radarr:
