- name: Create NGINX structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    recurse: true
  with_items:
    - path: '/data/DockerMounts/NGINX/Config'
      mode: 770
      owner: NGINX
      group: NGINX
