- name: Create Radarr structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    recurse: "{{ item.recurse }}"
  with_items:
    - path: '/data/DockerMounts/Radarr'
      mode: 770
      owner: Radarr
      group: MediaServices
      recurse: False
    - path: '/data/DockerMounts/Radarr/Config'
      mode: 770
      owner: Radarr
      group: MediaServices
      recurse: False

- name: Create Radarr symlink
  file:
    src: /data/Media
    dest: /data/DockerMounts/Radarr/Media
    state: link


- name: Run Radarr docker-compose
  docker_service:
    project_name: radarr
    definition:
      version: '2'
      networks:
        radarr:

      services:
        app:
          image: linuxserver/radarr
          restart: always
          environment:
            - PUID=2003
            - PGID=2004
          volumes:
            - '/dev/rtc:/dev/rtc:ro'
            - '/etc/localtime:/etc/localtime:ro'
            - '/data/DockerMounts/Radarr/Config:/config'
            - '/data/DockerMounts/Radarr/Media:/media'
          networks:
            radarr:
              aliases:
                - radarr
