- name: Create Sonarr structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    recurse: "{{ item.recurse }}"
  with_items:
    - path: '/data/DockerMounts/Sonarr'
      mode: 770
      owner: Sonarr
      group: MediaServices
      recurse: False
    - path: '/data/DockerMounts/Sonarr/Config'
      mode: 770
      owner: Sonarr
      group: MediaServices
      recurse: True


- name: Create Sonarr symlink
  file:
    src: /data/Media
    dest: /data/DockerMounts/Sonarr/Media
    state: link
    owner: Sonarr
    group: MediaServices
