---
- name: Add Media Server Groups
  group:
    name: NGINX
    gid: 2001
    state: present

- name: Add Wordpress Server Users
  user:
    name: NGINX
    uid: 2001
    shell: /bin/false
    group: NGINX
    state: present

- name: Create Wordpress structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
    owner: 'NGINX'
    group: 'NGINX'
    recurse: true
  with_items:
    - path: '/data/DockerMounts/wordpress_db'
    - path: '/data/DockerMounts/wordpress_db/Config'
    - path: '/data/DockerMounts/wordpress'
    - path: '/data/DockerMounts/wordpress/conf.d'
    - path: '/data/DockerMounts/wordpress/backups'

- name: Create and start DB container
  docker_container:
    name: wordpress-db
    image: linuxserver/mariadb
    pull: yes
    env:
      PUID: 2001
      PGID: 2001
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - '/dev/rtc:/dev/rtc:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - '/data/DockerMounts/wordpress_db/Config:/config'
    restart_policy: unless-stopped
    networks:
      - name: wordpress
    state: started

- name: Create and start Wordpress FPM container
  docker_container:
    name: wordpress-julesinabox
    image: wordpress
    pull: yes
    env:
      VIRTUAL_HOST: "www.{{domain}},{{domain}}"
      LETSENCRYPT_HOST: "www.{{domain}},{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
      CERT_NAME: "www.julesinabox.com"
    volumes:
      - '/dev/rtc:/dev/rtc:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - '/data/DockerMounts/wordpress/www/julesinabox:/var/www/html'
    restart_policy: unless-stopped
    networks:
      - name: proxy
      - name: wordpress
    state: started

- name: Create and start Wordpress FPM container
  docker_container:
    name: wordpress-thekiwidiaries
    image: wordpress
    pull: yes
    env:
      VIRTUAL_HOST: "www.thekiwidiaries.com,thekiwidiaries.com"
      LETSENCRYPT_HOST: "www.thekiwidiaries.com,thekiwidiaries.com"
      LETSENCRYPT_EMAIL: "{{email}}"
      CERT_NAME: "www.thekiwidiaries.com"
    volumes:
      - '/dev/rtc:/dev/rtc:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - '/data/DockerMounts/wordpress/www/thekiwidiaries:/var/www/html'
    restart_policy: unless-stopped
    networks:
      - name: proxy
      - name: wordpress
    state: started
