- name: Add Wordpress Server Users
  tags:
    - users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    shell: /bin/false
    group: NGINX
    state: present
  with_items:
    - { name: 'Wordpress', uid: 2005 }
    - { name: 'NGINX', uid: 2006 }

- name: Create Wordpress structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    recurse: true
  with_items:
    - path: '/data/DockerMounts/wordpress_db'
      mode: 770
      owner: 'Wordpress'
      group: 'NGINX'
    - path: '/data/DockerMounts/wordpress_db/Config'
      mode: 770
      owner: Wordpress
      group: NGINX
    - path: '/data/DockerMounts/wordpress_nginx'
      mode: 770
      owner: Wordpress
      group: NGINX
    - path: '/data/DockerMounts/wordpress_nginx/Config'
      mode: 770
      owner: Wordpress
      group: NGINX
    - path: '/data/DockerMounts/NGINX/Config'
      mode: 770
      owner: NGINX
      group: NGINX
    - path: '/data/DockerMounts/NGINX/Config'
      mode: 770
      owner: NGINX
      group: NGINX

- name: Clone Wordpress directory
  git:
    repo: "{{ wordpress_docker_git }}"
    dest: "{{ wordpress_docker_git_local }}"
  notify:
    - Build pecigonzalo/wordpress image

- name: Build pecigonzalo/wordpress image
  docker_image:
     path: "{{ wordpress_docker_git_local }}"
     name: pecigonzalo/wordpress

- name: Run wordpress docker-compose
  tags:
    - docker-compose
  docker_service:
    project_name: wordpress
    definition:
      version: '2'
      networks:
        wordpress:
        db:

      services:
        wordpress.db:
          image: linuxserver/mariadb
          restart: always
          environment:
            - PUID=2005
            - PGID=2005
            - MYSQL_ROOT_PASSWORD=wordpress
          volumes:
            - '/dev/rtc:/dev/rtc:ro'
            - '/etc/localtime:/etc/localtime:ro'
            - '/data/DockerMounts/wordpress_db/Config:/config'
          networks:
            db:
              aliases:
                - db
        web:
          image: pecigonzalo/wordpress
          restart: always
          environment:
            - PUID=2005
            - PGID=2005
          volumes:
            - '/dev/rtc:/dev/rtc:ro'
            - '/etc/localtime:/etc/localtime:ro'
            - '/data/DockerMounts/NGINX/Config/backups:/config/ckups'
            - '/data/DockerMounts/NGINX/Config/www:/config/www'
          networks:
            wordpress:
              aliases:
                - wordpress
            db:
