---
- name: Add Media Server Groups
  group:
    name: NGINX
    gid: 2001
    state: present

- name: Add Wordpress Server Users
  user:
    name: NGINX
    uid: 2001
    shell: /bin/false
    group: NGINX
    state: present

- name: Create Wordpress structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
    owner: "NGINX"
    group: "NGINX"
  with_items:
    - path: "/data/DockerMounts/wordpress_db"
    - path: "/data/DockerMounts/wordpress_db/Config"
    - path: "/data/DockerMounts/wordpress"

- name: Create Wordpress www structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
    owner: "www-data"
    group: "www-data"
    recurse: true
  with_items:
    - path: "/data/DockerMounts/wordpress/www"

- name: Create docker networks
  docker_network:
    name: "{{ item.name }}"
  with_items:
    - name: wordpress

- name: Create and start DB container
  community.docker.docker_container:
    name: wordpress-db
    image: linuxserver/mariadb
    env:
      PUID: "2001"
      PGID: "2001"
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - "/data/DockerMounts/wordpress_db/Config:/config"
    networks:
      - name: wordpress

- name: Create and start JulesInABox FPM container
  community.docker.docker_container:
    name: wordpress-julesinabox
    image: wordpress
    labels:
      traefik.enable: "true"
      traefik.http.routers.julesinabox.rule: "Host(`www.{{domain}}`) || Host(`{{domain}}`)"
      traefik.http.routers.julesinabox.tls.certresolver: "letsencrypt"
    volumes:
      - "/data/DockerMounts/wordpress/www/julesinabox:/var/www/html"
    networks:
      - name: proxy
      - name: wordpress

- name: Create and start Portfolio FPM container
  community.docker.docker_container:
    name: wordpress-portfolio
    image: wordpress
    labels:
      traefik.enable: "true"
      traefik.http.routers.portfolio.rule: "Host(`www.portfolio.{{domain}}`) || Host(`portfolio.{{domain}}`)"
      traefik.http.routers.portfolio.tls.certresolver: "letsencrypt"
    volumes:
      - "/data/DockerMounts/wordpress/www/portfolio:/var/www/html"
    networks:
      - name: proxy
      - name: wordpress

- name: Create and start TKD FPM container
  community.docker.docker_container:
    name: wordpress-thekiwidiaries
    image: wordpress
    labels:
      traefik.enable: "true"
      traefik.http.routers.thekiwidiaries.rule: "Host(`www.thekiwidiaries.com`) || Host(`thekiwidiaries.com`)"
      traefik.http.routers.thekiwidiaries.tls.certresolver: "letsencrypt"
    volumes:
      - "/data/DockerMounts/wordpress/www/thekiwidiaries:/var/www/html"
    networks:
      - name: proxy
      - name: wordpress
