---
- name: Create tautulli directories
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
    owner: MediaServices
    group: MediaServices
    recurse: False
  with_items:
    - path: "/data/DockerMounts/tautulli/Config"

- name: Create and start container
  community.docker.docker_container:
    name: tautulli
    image: tautulli/tautulli
    env:
      PUID: "2000"
      PGID: "2000"
    labels:
      traefik.enable: "true"
      traefik.http.routers.tautulli.rule: "Host(`tautulli.{{domain}}`)"
      traefik.http.routers.tautulli.tls.certresolver: "letsencrypt"
      traefik.http.routers.tautulli.middlewares: "authelia@docker"
    volumes:
      - "/data/DockerMounts/tautulli/Config:/config"
      - "/data/DockerMounts/Plex/Config/Library/Application Support/Plex Media Server/Logs:/logs:ro"
    networks:
      - name: proxy
      - name: plex
