---
- name: Create Radarr structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
    owner: MediaServices
    group: MediaServices
    recurse: False
  with_items:
    - path: "/data/DockerMounts/Radarr"
    - path: "/data/DockerMounts/Radarr/Config"

- name: Create and start container
  community.docker.docker_container:
    name: radarr
    image: linuxserver/radarr
    env:
      PUID: "2000"
      PGID: "2000"
    labels:
      traefik.enable: "true"
      traefik.http.routers.radarr.rule: "Host(`radarr.{{domain}}`)"
      traefik.http.routers.radarr.tls.certresolver: "letsencrypt"
      traefik.http.routers.radarr.middlewares: "authelia@docker"
      traefik.http.services.radarr.loadbalancer.server.port: "7878"
    volumes:
      - "/data/DockerMounts/Radarr/Config:/config"
      - "/data/Media:/media"
    networks:
      - name: proxy
      - name: plex
