---
- name: Update packages
  apt:
    update_cache: yes

- name: Upgrade packages
  apt:
    upgrade: dist

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Enable sysctl setting
  sysctl:
    sysctl_file: /etc/sysctl.d/90-ansible.conf
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.tcp_window_scaling
      value: 1
    - name: net.core.rmem_max
      value: 67108864
    - name: net.core.wmem_max
      value: 67108864
    - name: net.ipv4.tcp_rmem
      value: "4096 87380 33554432"
    - name: net.ipv4.tcp_wmem
      value: "4096 87380 33554432"
    - name: net.ipv4.tcp_congestion_control
      value: bbr
    - name: fs.file-max
      value: 100000
    - name: vm.swappiness
      value: 10
    - name: vm.dirty_background_ratio
      value: 10
    - name: vm.dirty_ratio
      value: 15
    - name: net.core.somaxconn
      value: 1024
    - name: net.core.netdev_max_backlog
      value: 50000
    - name: net.ipv4.tcp_max_syn_backlog
      value: 30000
    - name: net.ipv4.tcp_max_tw_buckets
      value: 2000000
    - name: net.ipv4.tcp_tw_reuse
      value: 1
    - name: net.ipv4.tcp_mtu_probing
      value: 1
    - name: net.ipv4.tcp_sack
      value: 1
    - name: net.ipv4.tcp_adv_win_scale
      value: 2
    - name: net.ipv4.tcp_rfc1337
      value: 1
    - name: net.ipv4.tcp_fin_timeout
      value: 10
    - name: net.ipv4.tcp_slow_start_after_idle
      value: 0
    - name: net.ipv4.udp_rmem_min
      value: 8192
    - name: net.ipv4.udp_wmem_min
      value: 8192
    - name: net.ipv4.conf.all.accept_source_route
      value: 0
    - name: net.ipv4.conf.all.accept_redirects
      value: 0
    - name: net.ipv4.conf.all.secure_redirects
      value: 0
    - name: net.core.default_qdisc
      value: fq

- name: Set sysctl vars
  command: sysctl --system

- debug:
    msg: "System mounts: are {{ ansible_mounts }}"

- name: Set noatime,nobarrier opts for / mount
  mount:
    path: /
    opts: defaults,noatime,nobarrier
    state: present
    fstype: ext4
    src: "{{ item.device }}"
  with_items:
    - "{{ ansible_mounts }}"
  when: "item.mount == '/'"

- name: Mount Data volume
  mount:
    path: /data
    src: UUID="b584c764-ec62-4014-9899-b5ed6d23c60c"
    fstype: xfs
    state: present

- iptables:
    action: insert
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- iptables:
    action: insert
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT
