---
- name: Create unifi structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
    owner: root
    group: root
    recurse: False
  with_items:
    - path: "/data/DockerMounts/unifi"

- name: Create and start container
  community.docker.docker_container:
    name: unifi
    image: "linuxserver/unifi-controller"
    published_ports:
      - "8843:8843"
      - "8080:8080"
      - "8081:8081"
      - "8880:8880"
      - "3478:3478/udp"
      - "10001:10001/udp"
    labels:
      traefik.enable: "true"
      traefik.http.routers.unifi.rule: "Host(`control.{{domain}}`)"
      traefik.http.routers.unifi.tls.certresolver: "letsencrypt"
      traefik.http.routers.unifi.middlewares: "authelia@docker"
      traefik.http.services.unifi.loadbalancer.server.port: "8443"
      traefik.http.services.unifi.loadbalancer.server.scheme: https
    volumes:
      - "/data/DockerMounts/unifi:/config"
    networks:
      - name: proxy
