---
- name: Create Sonarr structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
    owner: MediaServices
    group: MediaServices
    recurse: False
  with_items:
    - path: "/data/DockerMounts/Sonarr"
    - path: "/data/DockerMounts/Sonarr/Config"

- name: Create and start container
  community.docker.docker_container:
    name: sonarr
    image: "linuxserver/sonarr"
    env:
      PUID: "2000"
      PGID: "2000"
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarr.rule: "Host(`sonarr.{{domain}}`)"
      traefik.http.routers.sonarr.tls.certresolver: "letsencrypt"
      traefik.http.routers.sonarr.middlewares: "authelia@docker"
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"
    volumes:
      - "/data/DockerMounts/Sonarr/Config:/config"
      - "/data/Media:/media"
    networks:
      - name: proxy
      - name: plex
