---
- name: Create Portainer structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
    owner: MediaServices
    group: MediaServices
    recurse: False
  with_items:
    - path: "/data/DockerMounts/Portainer"

- name: Create and start container
  community.docker.docker_container:
    name: portainer
    image: "portainer/portainer"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/data/DockerMounts/Portainer:/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.rule: "Host(`portainer.{{domain}}`)"
      traefik.http.routers.portainer.tls.certresolver: "letsencrypt"
      traefik.http.routers.portainer.middlewares: "authelia@docker"
    networks:
      - name: proxy
