---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: bazarr

- name: Create Bazarr structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
    owner: MediaServices
    group: MediaServices
    recurse: False
  with_items:
    - path: "/data/DockerMounts/Bazarr"
    - path: "/data/DockerMounts/Bazarr/Config"

- name: Create and start container
  docker_container:
    networks_cli_compatible: yes
    name: bazarr
    image: "linuxserver/bazarr"
    pull: yes
    env:
      PUID: "2000"
      PGID: "2000"
      VIRTUAL_HOST: "bazarr.{{domain}}"
      VIRTUAL_PORT: "6767"
      LETSENCRYPT_HOST: "bazarr.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes:
      - "/dev/rtc:/dev/rtc:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/data/DockerMounts/Bazarr/Config:/config"
      - "/data/Media:/media"
    purge_networks: yes
    networks:
      - name: proxy
      - name: plex
    restart_policy: unless-stopped
    state: started
