---
- name: Create Bazarr structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
    owner: MediaServices
    group: MediaServices
    recurse: False
  with_items:
    - path: "/data/DockerMounts/Bazarr"
    - path: "/data/DockerMounts/Bazarr/Config"

- name: Create and start container
  community.docker.docker_container:
    name: bazarr
    image: "linuxserver/bazarr:development"
    env:
      PUID: "2000"
      PGID: "2000"
    labels:
      traefik.enable: "true"
      traefik.http.routers.bazarr.rule: "Host(`bazarr.{{domain}}`)"
      traefik.http.routers.bazarr.tls.certresolver: "letsencrypt"
      traefik.http.routers.bazarr.middlewares: "authelia@docker"
    volumes:
      - "/data/DockerMounts/Bazarr/Config:/config"
      - "/data/Media:/media"
    networks:
      - name: proxy
      - name: plex
