name             'mothership'
maintainer       'Gonzalo Peci'
maintainer_email 'email@emial.com'
license          'All rights reserved'
description      'Installs/Configures mothership'
long_description 'No Description'
version          '0.1.0'
depends 'docker', '~> 1.0'
depends 'git'
