---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: ssh

- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
       - git
       - bc
       - jq
       - wget
       - curl
       - unattended-upgrades
       - apt-listchanges
       - apt-transport-https
       - ca-certificates
       - gnupg2
       - software-properties-common
       - acpid
       - dkms
       - python-pip
       - dnsutils
       - iotop
       - htop
       - glances
       - iftop
       - ngrep
       - iptraf
       - tree
       - ncdu
       - sysstat
       - mlocate
       - ntpdate
       - iptables-persistent
       - vim
       - tmux

- name: Install hostess
  get_url:
    url:  https://github.com/cbednarski/hostess/releases/download/v0.3.0/hostess_linux_amd64
    dest: /usr/local/bin/hostess
    mode: 0755
    owner: root
    group: root
    force: yes
    validate_certs: no
  tags: update-hostess

- name: Install ngrok
  unarchive:
    src: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
    dest: /usr/local/bin
    copy: no
    mode: 0775
    validate_certs: no
  tags: update-ngrok
