---
- name: Install required system packages
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: 86400
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - python-docker

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present

- name: Add official repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/raspbian/ {{ ansible_distribution_release }} stable"
    state: present

- name: Install docker-ce
  apt:
    name: docker-ce
    state: latest
    install_recommends: no
    update_cache: yes
    cache_valid_time: 86400

- name: Check docker daemon.json exists
  stat:
    path: /etc/docker/daemon.json
  register: docker_daemon

- name: Stop docker to enable overlay2
  systemd: state=stopped name=docker enabled=yes
  when: docker_daemon.stat.exists == False

- name: Import daemon.json
  copy: "src=daemon.json dest=/etc/docker/daemon.json force=yes mode=0775"
  when: docker_daemon.stat.exists == False

- name: Start docker
  systemd: state=started name=docker enabled=yes
  when: docker_daemon.stat.exists == False
