---
- name: Add Media Server Groups
  tags:
    - users
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  with_items:
    - { name: 'MediaServices', gid: 2000 }

- name: Add Media Server Users
  tags:
    - users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    shell: /bin/false
    group: MediaServices
    state: present
  with_items:
    - { name: 'MediaServices', uid: 2000 }

- name: Create docker networks
  docker_network:
    name: "{{ item.name }}"
  with_items:
    - name: proxy
    - name: plex
