- name: Create Plex structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    recurse: "{{ item.recurse }}"
  with_items:
    - path: '/data/DockerMounts/Plex'
      mode: 770
      owner: Plex
      group: MediaServices
      recurse: False
    - path: '/data/DockerMounts/Plex/Config'
      mode: 770
      owner: Plex
      group: MediaServices
      recurse: True
    - path: '/data/DockerMounts/tautulli/Config'
      mode: 770
      owner: Plex
      group: MediaServices
      recurse: True

- name: Create Plex symlink
  file:
    src: /data/Media
    dest: /data/DockerMounts/Plex/Media
    owner: Plex
    group: MediaServices
    state: link
