- name: Create Radarr structure
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    recurse: "{{ item.recurse }}"
  with_items:
    - path: '/data/DockerMounts/Radarr'
      mode: 770
      owner: Radarr
      group: MediaServices
      recurse: False
    - path: '/data/DockerMounts/Radarr/Config'
      mode: 770
      owner: Radarr
      group: MediaServices
      recurse: True

- name: Create Radarr symlink
  file:
    src: /data/Media
    dest: /data/DockerMounts/Radarr/Media
    state: link
    owner: Radarr
    group: MediaServices
