---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: wallabag

# - name: Create wallabag directories
#   file:
#     path: "{{ item.path }}"
#     state: directory
#     # mode: 0775
#     # owner: MediaServices
#     # group: MediaServices
#     recurse: False
#   with_items:
#     - path: '/data/DockerMounts/wallabag'
#     - path: '/data/DockerMounts/wallabag/data'
#     - path: '/data/DockerMounts/wallabag/images'
#     - path: '/data/DockerMounts/wallabag/db'

- name: Create redis container
  docker_container:
    name: wallabag-redis
    image: redis:alpine
    pull: yes
    purge_networks: yes
    networks:
      - name: wallabag
    state: started
    restart_policy: unless-stopped

- name: Create and start DB container
  docker_container:
    name: wallabag-db
    image: mariadb
    pull: yes
    env:
      MYSQL_ROOT_PASSWORD: wallaroot
    volumes:
      - "/data/DockerMounts/wallabag/db:/var/lib/mysql"
    restart_policy: unless-stopped
    purge_networks: yes
    networks:
      - name: wallabag
    state: started

- name: Create wallabag container
  docker_container:
    name: wallabag
    image: "wallabag/wallabag"
    pull: yes
    env:
      VIRTUAL_HOST: "wallabag.{{domain}}"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "wallabag.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
      MYSQL_ROOT_PASSWORD: "wallaroot"
      SYMFONY__ENV__DATABASE_DRIVER: "pdo_mysql"
      SYMFONY__ENV__DATABASE_HOST: "wallabag-db"
      SYMFONY__ENV__DATABASE_PORT: 3306
      SYMFONY__ENV__DATABASE_NAME: "wallabag"
      SYMFONY__ENV__DATABASE_USER: "wallabag"
      SYMFONY__ENV__DATABASE_PASSWORD: "wallapass"
      SYMFONY__ENV__REDIS_HOST: "wallabag-redis"
      SYMFONY__ENV__DOMAIN_NAME: "https://wallabag.{{domain}}"
      SYMFONY__ENV__FOSUSER_REGISTRATION: "false"
      SYMFONY__ENV__FOSUSER_CONFIRMATION: "false"
      POPULATE_DATABASE: "false"
    volumes:
      - "/data/DockerMounts/wallabag/images:/var/www/wallabag/web/assets/images"
    purge_networks: yes
    networks:
      - name: proxy
      - name: wallabag
    state: started
    restart_policy: unless-stopped
