---
# - name: Create wallabag directories
#   file:
#     path: "{{ item.path }}"
#     state: directory
#     # mode: 0775
#     # owner: MediaServices
#     # group: MediaServices
#     recurse: False
#   with_items:
#     - path: '/data/DockerMounts/wallabag'
#     - path: '/data/DockerMounts/wallabag/data'
#     - path: '/data/DockerMounts/wallabag/images'
#     - path: '/data/DockerMounts/wallabag/db'

- name: Create redis container
  community.docker.docker_container:
    name: wallabag-redis
    image: redis:alpine
    networks:
      - name: wallabag

- name: Create and start DB container
  community.docker.docker_container:
    name: wallabag-db
    image: mariadb
    env:
      MYSQL_ROOT_PASSWORD: wallaroot
    volumes:
      - "/data/DockerMounts/wallabag/db:/var/lib/mysql"
    networks:
      - name: wallabag

- name: Create wallabag container
  community.docker.docker_container:
    name: wallabag
    image: "wallabag/wallabag"
    env:
      MYSQL_ROOT_PASSWORD: "wallaroot"
      SYMFONY__ENV__DATABASE_DRIVER: "pdo_mysql"
      SYMFONY__ENV__DATABASE_HOST: "wallabag-db"
      SYMFONY__ENV__DATABASE_PORT: "3306"
      SYMFONY__ENV__DATABASE_NAME: "wallabag"
      SYMFONY__ENV__DATABASE_USER: "wallabag"
      SYMFONY__ENV__DATABASE_PASSWORD: "wallapass"
      SYMFONY__ENV__REDIS_HOST: "wallabag-redis"
      SYMFONY__ENV__DOMAIN_NAME: "https://wallabag.{{domain}}"
      SYMFONY__ENV__FOSUSER_REGISTRATION: "false"
      SYMFONY__ENV__FOSUSER_CONFIRMATION: "false"
      POPULATE_DATABASE: "false"
    labels:
      traefik.enable: "true"
      traefik.http.routers.wallabag.rule: "Host(`wallabag.{{domain}}`)"
      traefik.http.routers.wallabag.tls.certresolver: "letsencrypt"
      traefik.http.routers.wallabag.middlewares: "authelia@docker"
    volumes:
      - "/data/DockerMounts/wallabag/images:/var/www/wallabag/web/assets/images"
    networks:
      - name: proxy
      - name: wallabag
