#!/usr/bin/env ruby

source 'https://supermarket.chef.io'

cookbook 'docker'
cookbook 'fail2ban'

# Local cookbooks
list = Dir.entries('./cookbooks/').select { |f| !File.directory? f }
           .reject{ |f| f.start_with? '.' }
list.each do |book|
  cookbook book, path: "cookbooks/#{book}"
end
